# Generated by Django 5.0.2 on 2024-02-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='ci',
            field=models.IntegerField(),
        ),
    ]
